### ISSUE TITLE
将.vue文件关联weex后文件图标显示异常

### ISSUE THREAD

**Issue by aremars** [weex-cli/vscode-weex#2]
vscode使用按照说明进行了vue文件跟weex的关联后，vue文件的图标就显示成默认的文件图标了（不是vue文件图标），不影响使用但总感觉有点不爽，请问下是哪里设置有问题吗？

**Comment by GGICE** [comment]
![screen shot 2019-02-26 at 10 51 08 am](https://user-images.githubusercontent.com/3450419/53384035-80d74980-39b4-11e9-865d-561d72a78b1d.png)

我这里看起来是正常的，图标是指我标准处的图标吗，可能和图标主题也有关
