### ISSUE TITLE
vscode run ios 找不到设备，

### ISSUE THREAD

**Issue by aadd1989** [weex-cli/vscode-weex#3]
![image](https://user-images.githubusercontent.com/10625335/56358870-8f065100-6212-11e9-86ec-79c614735556.png)

Xcode  Version 9.4.1

pod install 已安装 并且 build success

**Comment by GGICE** [comment]
可以再提供下，Run IOS 时的报错吗？

**Comment by aadd1989** [comment]
> 可以再提供下，Run IOS 时的报错吗？

![image](https://user-images.githubusercontent.com/10625335/56403417-cff27a00-6293-11e9-9194-b9b7ada54f6a.png)

**Comment by aadd1989** [comment]
问题已解决，
![image](https://user-images.githubusercontent.com/10625335/56403576-7dfe2400-6294-11e9-8710-56bf7f60eaa3.png)
解决办法：
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/ 

Thanks !
